### ISSUE TITLE
Will return list() for anything Falsey (instead of only for None)

### ISSUE THREAD

**Issue by ldunham1** [friedererdmann/pymxs_stubs#10]
https://github.com/friedererdmann/pymxs_stubs/blob/84d410c46d4718d7c0928574d12740100574a947/pyi_generator.py#L10

**Comment by friedererdmann** [comment]
Thanks for spotting this! Will get to it asap

**Comment by friedererdmann** [comment]
fixed in 4c6ca407a4f879f708c6f63ed9f22cc6ec74b64e
